version: '3.9'
services:
  django:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server/bank:/bank
    depends_on:
      - db

  bank-angular:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
      

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: 1111      
      POSTGRES_DB: q_bank          
    ports:
      - "5432:5432"
