# Generated by Django 5.1.4 on 2024-12-20 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=555)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=150)),
                ('lvl_order', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardRequestBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=555)),
                ('card_lvl', models.CharField(max_length=555)),
                ('card_stap_type', models.CharField(max_length=555)),
                ('card_num', models.CharField(max_length=555)),
                ('cvv', models.CharField(max_length=555)),
                ('exp_date', models.CharField(max_length=555)),
                ('card_type', models.CharField(max_length=555)),
                ('used_value', models.IntegerField()),
                ('total_aspect_value', models.IntegerField()),
                ('create_time', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=255)),
                ('timestamp', models.DecimalField(decimal_places=10, max_digits=20)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymantGateWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=255, unique=True)),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateway', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=555, unique=True)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferTempToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=555, unique=True)),
                ('token_user', models.CharField(max_length=255)),
                ('limite', models.DecimalField(decimal_places=0, max_digits=150)),
                ('access', models.BooleanField()),
                ('exp_date', models.DecimalField(decimal_places=0, max_digits=150)),
                ('used', models.DecimalField(decimal_places=0, max_digits=150)),
                ('exp_date_used', models.DecimalField(decimal_places=0, max_digits=150)),
                ('api_name', models.CharField(max_length=255)),
                ('create_timespan', models.DecimalField(decimal_places=0, max_digits=150)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('account_pin', models.CharField(max_length=255, null=True)),
                ('account_lvl', models.DecimalField(decimal_places=10, max_digits=20)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
